repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
          - id: check-byte-order-marker
          - id: trailing-whitespace
          - id: mixed-line-ending
            args: ["--fix=lf"]
          - id: check-merge-conflict
          - id: check-json
          - id: check-yaml
          - id: detect-aws-credentials
          - id: detect-private-key
          - id: pretty-format-json
            args: ["--autofix", "--no-sort-keys", "--indent=4"]
    - repo: https://github.com/prettier/prettier
      rev: 1.16.2
      hooks:
          - id: prettier
            files: \.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v5.16.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@4.19.1
                - eslint-plugin-prettier@2.7.0
                - prettier@1.16.4
    - repo: https://github.com/awebdeveloper/pre-commit-stylelint
      rev: 0.0.2
      hooks:
          - id: stylelint
            additional_dependencies:
                - stylelint@9.10.1
                - stylelint-config-prettier@3.3.0
                - stylelint-config-recommended@2.1.0
